// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjLookday.Models;

public partial class BookingState
{
    public int BookingStatesId { get; set; }

    public string States { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}